/*
Pulp 3 API

Testing RepositoriesGemVersionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/osbuild/pulp-client/pulpclient"
)

func Test_pulpclient_RepositoriesGemVersionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RepositoriesGemVersionsAPIService RepositoriesGemGemVersionsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryVersionHref string

		resp, httpRes, err := apiClient.RepositoriesGemVersionsAPI.RepositoriesGemGemVersionsDelete(context.Background(), gemGemRepositoryVersionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemVersionsAPIService RepositoriesGemGemVersionsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesGemVersionsAPI.RepositoriesGemGemVersionsList(context.Background(), gemGemRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemVersionsAPIService RepositoriesGemGemVersionsRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryVersionHref string

		resp, httpRes, err := apiClient.RepositoriesGemVersionsAPI.RepositoriesGemGemVersionsRead(context.Background(), gemGemRepositoryVersionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemVersionsAPIService RepositoriesGemGemVersionsRepair", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryVersionHref string

		resp, httpRes, err := apiClient.RepositoriesGemVersionsAPI.RepositoriesGemGemVersionsRepair(context.Background(), gemGemRepositoryVersionHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
