/*
Pulp 3 API

Testing PublicationsGemAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/osbuild/pulp-client/pulpclient"
)

func Test_pulpclient_PublicationsGemAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicationsGemAPIService PublicationsGemGemCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicationsGemAPI.PublicationsGemGemCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationsGemAPIService PublicationsGemGemDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemPublicationHref string

		httpRes, err := apiClient.PublicationsGemAPI.PublicationsGemGemDelete(context.Background(), gemGemPublicationHref).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationsGemAPIService PublicationsGemGemList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicationsGemAPI.PublicationsGemGemList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicationsGemAPIService PublicationsGemGemRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemPublicationHref string

		resp, httpRes, err := apiClient.PublicationsGemAPI.PublicationsGemGemRead(context.Background(), gemGemPublicationHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
