/*
Pulp 3 API

Testing RepositoriesGemAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pulpclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/osbuild/pulp-client/pulpclient"
)

func Test_pulpclient_RepositoriesGemAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RepositoriesGemAPIService RepositoriesGemGemCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RepositoriesGemAPI.RepositoriesGemGemCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemAPIService RepositoriesGemGemDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesGemAPI.RepositoriesGemGemDelete(context.Background(), gemGemRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemAPIService RepositoriesGemGemList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RepositoriesGemAPI.RepositoriesGemGemList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemAPIService RepositoriesGemGemModify", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesGemAPI.RepositoriesGemGemModify(context.Background(), gemGemRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemAPIService RepositoriesGemGemPartialUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesGemAPI.RepositoriesGemGemPartialUpdate(context.Background(), gemGemRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemAPIService RepositoriesGemGemRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesGemAPI.RepositoriesGemGemRead(context.Background(), gemGemRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemAPIService RepositoriesGemGemSync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesGemAPI.RepositoriesGemGemSync(context.Background(), gemGemRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoriesGemAPIService RepositoriesGemGemUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var gemGemRepositoryHref string

		resp, httpRes, err := apiClient.RepositoriesGemAPI.RepositoriesGemGemUpdate(context.Background(), gemGemRepositoryHref).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
